syntax = "proto3";

option java_multiple_files = true;
option java_package = "student";
option java_outer_classname = "StudentServiceProto";

service StudentService {
  rpc CreateStudent (AddStudentRequest) returns (AddStudentResponse);
  rpc GetStudent (GetStudentRequest) returns (GetStudentResponse);
}

message AddStudentRequest {
  int32 roll_number = 1;
  string full_name = 2;
  int32 age = 3;
  string address = 4;
  repeated string courses = 5;
}

message AddStudentResponse {
  string full_name = 1;
  int32 roll_number = 2;
  string message = 3;
  bool success = 4;
  string error_message = 5;
}

message GetStudentRequest {}

message StudentMessage {
  int32 roll_number = 1;
  string full_name = 2;
  int32 age = 3;
  string address = 4;
  repeated string courses = 5;
}

message GetStudentResponse {
  repeated StudentMessage students = 1;
}